### ISSUE TITLE
Customizer don't show my header logo and login logo

### ISSUE THREAD

**Issue by mohabaee** [creecros/Customizer#134] opened 2022-06-26 15:29 UTC
Hello
My customizer don't show my header logo and also my logo on login page. Also when I go to it's setting page and click on image assets and settings shows these errors:
Header Avatar Icon

Deprecated: Required parameter $size follows optional parameter $css in /home2/jdiutir/public_html/kanban/plugins/Customizer/Helper/DynamicAvatar.php on line 26

Deprecated: Required parameter $size follows optional parameter $css in /home2/jdiutir/public_html/kanban/plugins/Customizer/Helper/DynamicAvatar.php on line 47
Please help me to solve it. 
Thanks

**Comment by creecros** [comment] 2022-06-26 15:52
looks like php errors.
what version of customizer, and what is you servers php version?

**Comment by mohabaee** [comment] 2022-06-26 17:16
I use the last version of customizer and the PHP version on server is 8.0.2.

**Comment by creecros** [comment] 2022-06-26 22:51
that's interesting,  as I don't get any errors in php 8 with latest customizer....do me a a favor and screen shot the plugin version and tour server config from kanboard founding settings. then I can take a look at try8ng to reproduce.

**Comment by mohabaee** [comment] 2022-06-27 04:15
I have sent you some screenshots from your information that you had requested before.
![Uploading 1.JPG…]()
@creecros

**Comment by creecros** [comment] 2022-06-27 04:56
I'm not seeing any screenshots. and the only information you are giving me are warnings, not errors. also, if you look at the code of dynamicavatar.php, you will see that the optional parameters do come after the required parameters, so the warnings do not align with what I'm being told. help me, help you.

**Comment by mohabaee** [comment] 2022-06-27 05:22
https://file.io/TzfgELN3zPtj

**Comment by mohabaee** [comment] 2022-06-27 05:24
You can find screenshots in the link below:
https://file.io/TzfgELN3zPtj

**Comment by creecros** [comment] 2022-06-27 06:01
![image](https://user-images.githubusercontent.com/26339368/175869846-ecf29c07-ca19-4e5c-a905-f36e4ef8c27f.png)

you're making this somewhat difficult. paste the screenshot into the comment.

**Comment by mohabaee** [comment] 2022-06-27 06:45
Please follow these links below:
https://s6.uupload.ir/files/1_aqfa.jpg
https://s6.uupload.ir/files/2_lss1.jpg
https://s6.uupload.ir/files/3_o2nn.jpg

**Comment by creecros** [comment] 2022-09-26 12:07
Tested with:
```
Configuration
Application version: v1.2.23
PHP version: 8.1.9
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 5.10.102.1-microsoft-standard-WSL2
Database driver: sqlite
Database version: 3.38.5
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
```

no issue found with plugin.

**Comment by creecros** [comment] 2022-09-26 12:12
I lied, I did find something:
```
PHP message: PHP Deprecated:  Implicit conversion from float -0.5 to int loses precision in /var/www/app/app/Core/Thumbnail.php on line 130"

2022/09/26 12:04:12 [error] 15#15: *24 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Implicit conversion from float -0.5 to int loses precision in /var/www/app/app/Core/Thumbnail.php on line 130" while reading response header from upstream, client: 172.17.0.1, server: localhost, request: "GET /?controller=AvatarFileController&action=image&user_id=1&hash=38c767f0ba2714eabd07043c04195168&size=48 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.2:41980"
```

Will look into.

**Comment by creecros** [comment] 2022-11-02 13:57
> I lied, I did find something, but it appears to be in kanboard itself, will need to investigate:
> 
> ```
> PHP message: PHP Deprecated:  Implicit conversion from float -0.5 to int loses precision in /var/www/app/app/Core/Thumbnail.php on line 130"
> 
> 2022/09/26 12:04:12 [error] 15#15: *24 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Implicit conversion from float -0.5 to int loses precision in /var/www/app/app/Core/Thumbnail.php on line 130" while reading response header from upstream, client: 172.17.0.1, server: localhost, request: "GET /?controller=AvatarFileController&action=image&user_id=1&hash=38c767f0ba2714eabd07043c04195168&size=48 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.2:41980"
> ```
> 
> Will look into.
> 
> in console:
> 
> ```
>  GET http://192.168.1.2:41980/?controller=AvatarFileController&action=image&user_id=1&hash=76ecda9…&size=30 404
> ```

New pull request in Kanboard repo should take care of this once merged.

**Closed by creecros** 2022-11-02 13:57 UTC
